%-------------------------------------------------------
% Author: Brady M. Chisholm
% University of Minnesota Twin Cities, Dpt. of Neuroscience
% Date: 6.9.2025
%
% Description: 
%                            
%-------------------------------------------------------
function p4instruct(window, expParams)
    % Display experiment instructions
    p4instructions = ['Part Three of the Human Tetris Experiment!\n' ...
        'During this section of the experiment, your job will be to score as many points as possible \nby correctly matching Tetris pieces to their matching tableau.\n' ...
        'Each of the 7 pieces has 3 corresponding tableaus.\n' ...
        '\n 1) Perfect fit and match (max points)' ...
        '\n 2) Partial fit (some points awarded)' ...
        '\n 3) No fit (points awarded for correct rejections)' ...
        '\n 4) Garbage.\n\n' ...
        'If the piece has none of the above options available, the optimal option is to trash the piece.\n\n' ...
        'This may seem illogical, however if a match is not there, then any other option EXCEPT \n the GARBAGE would be like putting a square through a round hole, in a way.\n' ...
        'During this section, points will be awarded when you correctly identify a MATCH and GARBAGE tableau. \nYour score will be displayed during the fixation period.\n\n Press SPACE to begin!'];

    Screen('TextSize', window, 26);
    Screen('TextFont', window, 'Arial');
    DrawFormattedText(window, p4instructions, 'center', 'center', [1 1 1]);
    Screen('Flip', window);
    
    % Wait for key press
    KbStrokeWait;
end