function p4instruct(window, params)
    % Display experiment instructions
    p4instructions = ['Welcome to the Part Four of the Human Tetris Experiment!\n\n' ...
        'During this section of the experiment, your job will be to score as many points as possible by correctly identifying the Tetris pieces\n\nEach of the 7 pieces \n\n' ...
        '\n\n has 3 corresponding tableaus. \n' ...
        '\n 1) Perfect fit and match (max points)' ...
        '\n 2) Partial fit (some points awarded)' ...
        '\n 3) No fit (points awarded for correct rejections)' ...
        '\n 4) Garbage. If the piece has none of the above options available, the best option is to trash the piece. Points will be awarded'];

    Screen('TextSize', window, 24);
    Screen('TextFont', window, 'Arial');
    DrawFormattedText(window, p4instructions, 'center', 'center', [1 1 1]);
    Screen('Flip', window);
    
    % Wait for key press
    KbStrokeWait;
end